### ISSUE TITLE
sendPluginData with list broken?  `bad argument #3 to 'sendPluginData' (mumble.user expected, got table)`

### ISSUE THREAD

**Issue by hbeni** [bkacjios/lua-mumble#21]
Hi, i noticed the following issue: `bad argument #3 to 'sendPluginData' (mumble.user expected, got table)`

- I have code that updates a global `playback_targets` variable. It builds a table containing `mumble.user` objects:
  ```lua
  updateAllChannelUsersforSend = function(cl)
    print("udpate channelusers")
    local ch = cl:getChannel(fgcom.channel)
    local users = ch:getUsers()
    playback_targets = {}
    print("ok: "..ch:getName())
    for k,v in pairs(users) do
        print("  k="..tostring(k).."v="..tostring(v))
        table.insert(playback_targets, v)
    end
  end
  ```
- I have a function defined to send specific plugin data to that list:
  ```lua
  notifyUserdata = function(tgts)
    local msg = "CALLSIGN="..fgcom.callsign
    fgcom.dbg("Bot sets userdata: "..msg)
    client:sendPluginData("FGCOM:UPD_USR:0", msg, tgts)
  end
  ```

When invoking it, I get the error.
When inspecting using `inspect` module after the call to `updateAllChannelUsersforSend` , it prints indeed the populated table:
```lua
    updateAllChannelUsersforSend(client)
local inspect = require('inspect')
print(inspect(playback_targets));
    notifyUserdata(playback_targets)
```
```
udpate channelusers
ok: fgcom-mumble
  k=73v=mumble.user [73][D-EBHX]
  k=75v=mumble.user [75][FGCOM-Recorder]
  k=74v=mumble.user [74][FGCOM-Status]
{ <userdata 1>, <userdata 2>, <userdata 3> }
test/fgcom-fakepilot.bot.lua:194: bad argument #3 to 'sendPluginData' (mumble.user expected, got table)
```

**Comment by hbeni** [comment]
The code is pretty old, and I'm *very* sure it worked before...

**Comment by hbeni** [comment]
I bisected it; was introduced by 61691efacd76d

**Comment by hbeni** [comment]
OK, from what I understand, this not actually broken, but I need to pass the args different.

How can I pass the users of the table as variable argumentation?

**Comment by hbeni** [comment]
https://www.lua.org/pil/5.2.html

-> need to use `unpack()`

**Comment by hbeni** [comment]
Reopening: even with a simple example i don't get any data anymore:

Receiver bot, just dumps the data to terminal:
```lua
mumble = require("mumble")  -- get the mumble API

local host = "fgcom.hallinger.org"
local port = 64738
local cert = "bot.pem"
local key  = "bot.key"

print("connecting to "..host.." on port "..port.." (cert: "..cert.."; key: "..key..")")
local client = assert(mumble.connect(host, port, cert, key))
client:auth("test-rcv")
print("  connect and bind: OK")


client:hook("OnServerSync", function(client, event)
    print("Sync done; server greeted with: ", event.welcome_text)
           
    -- try to join fgcom-mumble channel
    local ch = client:getChannel("fgcom-mumble")
    event.user:move(ch)
    print("joined channel fgcom-mumble")
end)
    
    

client:hook("OnPluginData", function(client, event)
    --["sender"] = mumble.user sender, -- Who sent this data packet
	--["id"]     = Number id,          -- The data ID of this packet
	--["data"]   = String data,        -- The data sent (can be binary data)
	--["receivers"]				= {  -- A table of who is receiving this data
	--	[1] = mumble.user,
	--},
    print("DATA INCOMING FROM="..event.sender:getSession())
    print("  ID="..event.id)
    print("  DATA="..event.data)

end)

mumble.loop()
``` 


Sending bot, just spams data:
```lua
mumble = require("mumble")  -- get the mumble API

local host = "fgcom.hallinger.org"
local port = 64738
local cert = "bot.pem"
local key  = "bot.key"

print("connecting to "..host.." on port "..port.." (cert: "..cert.."; key: "..key..")")
local client = assert(mumble.connect(host, port, cert, key))
client:auth("test-send")
print("  connect and bind: OK")

local timer = mumble.timer()
client:hook("OnServerSync", function(client, event)
    print("Sync done; server greeted with: ", event.welcome_text)
           
    -- try to join fgcom-mumble channel
    local ch = client:getChannel("fgcom-mumble")
    event.user:move(ch)
    print("joined channel fgcom-mumble")
    
    o=0
    timer:start(function(t)
	    o=o+1
        print(o..": send plugin message to all users ")
        users = client:getUsers()
        i = 0
        for s,u in pairs(users) do
            i=i+1
            print("  "..i.." ("..s.."): "..u:getName())
            --client:sendPluginData("FGCOM:UPD_USR:0", "CALLSIGN=test-"..i, u)
        end
            
        client:sendPluginData("FGCOM:UPD_COM:0:0", "FRQ=123,PTT=0"..i, unpack(users))
        
    end, 1, 1)
    
    --segfault client:sendPluginData("FGCOM:UPD_LOC", "CALLSIGN=test", client:getUsers()) 

    print("send ok")
end)

mumble.loop()
```

**Comment by hbeni** [comment]
somehow it looks like `sendPluginData` is putting nothing on the wire...

**Comment by bkacjios** [comment]
I believe to have found the issue..

I check if the argument is a table rather than a userdata

https://github.com/bkacjios/lua-mumble/blob/a88e4319a8f1eb36b9ec545218a36468865fca32/mumble/client.c#L180

Theoretically, if you pass the session numbers instead of the user metatable it will work. I'll have a fix for this soon though.

**Comment by hbeni** [comment]
Hm, but when i pass the arguments (table of users) using the `unpack()`, it will sort-of-work again.
What then just does not work, is that nothing is sent anymore.

Or is this what you are talking about?

**Comment by bkacjios** [comment]
Basically, if your table contained the actual user metatable, it would ignore it. The varargs were accepting numbers (the clients session number) OR a mumble.user metatable object (in which it would get the session number from) but due to me checking the wrong type value of the vararg, it was ignoring it.

Either way, this should be fixed now.

**Comment by hbeni** [comment]
Will test this! Thank you for the fast fix!

**Comment by hbeni** [comment]
Hm. The bot pair i posted above still has the issue....

**Comment by hbeni** [comment]
Like you said, this works:
`client:sendPluginData("FGCOM:UPD_COM:0:0", "FRQ=123,PTT=0"..i, unpack({82,98}))`

But this not:
`client:sendPluginData("FGCOM:UPD_COM:0:0", "FRQ=123,PTT=0"..i, unpack(client:getUsers()))`

**Comment by bkacjios** [comment]
I think the problem is unpack(users) may not actually work, since it's keyvalues has the format of `[session] = user`
I think unpack only supports an ordered list when they keys increment by 1.

I just added the ability to pass a table to sendPluginData again, alongside the new behavior of allowing varargs as well. If you revert all your changes to your bot when using that latest commit, it should be working again.

**Comment by bkacjios** [comment]
Also, it may be worth mentioning, but I also added a method to the mumble.user metatable as well for sending plugin data directly to that user.

```
-- Transmit a plugin data packet to this user
mumble.user:sendPluginData(String dataID, String plugindata)
```

**Comment by hbeni** [comment]
Cool, I will try it and report back.
Thanks again for the quick fixes!

**Comment by hbeni** [comment]
Tried it:

:ok: This works (using the old fashioned table containing user objects):
```lua
users = client:getUsers()
u_tbl = {}
i = 0
for s,u in pairs(users) do
  i=i+1
  print("  "..i.." ("..s.."): "..u:getName())
  table.insert(u_tbl, u)
end
client:sendPluginData("FGCOM:UPD_USR:0", "CALLSIGN=test-"..i, u_tbl)
```


:stop_sign: This still doesn't (using the user table):
`client:sendPluginData("FGCOM:UPD_COM:0:0", "FRQ=123,PTT=0"..i, users)`


This is fine enough for me :) Thank you :)
But if you like, I can do more testing for the usertable invocation

**Comment by bkacjios** [comment]
That.. kind of makes sense actually why that second case doesn't work.

`client:getUsers()` returns a table in the format of..

```lua
{
    [session] = mumble.user,
    [session] = mumble.user,
    [session] = mumble.user,
}
```

When you pass this table to sendPluginData() it tries to get the length of the table using `lua_objlen`. The problem is, since we have unordered table keys, it can't get the length, and thus fails.

Maybe I should add a method like client:getUserList() that just returns a proper ipairs-able table of mumble.user's

Like..
```lua
{
    [1] = mumble.user,
    [2] = mumble.user,
    [3] = mumble.user,
}
```

**Comment by bkacjios** [comment]
I may also create a new meta object.. Something like..

```lua
local data = mumble.plugindata("FGCOM:UPD_USR:0")
data:setData("Hello world! {x=3, y=8}")
data:addUser(32) -- Session number
data:addUser(client.me) -- User object
data:addAllUsers() -- Adds all users in the server
data:addUsersIn(client.me:getChannel()) -- Adds all users in a given channel
data:clearUsers() -- Removes all users
client:sendPluginData(data)
```
You think this would make things easier and less ambiguous? I'm open to suggestions here, since you're the only person I know who's using this functionality.

**Comment by bkacjios** [comment]
Alright well, I decided on making `mumble.client:getUsers()` return an ordered table of users, rather than a key=session, value=user pair. This allows you to pass the table without modification to `mumble.client:sendPluginData()`

I removed the vararg functionality since `mumble.client:sendPluginData(String dataID, String plugindata, Table {mumble.user, ...})` is for sending data to multiple clients.

`mumble.user:sendPluginData(String dataID, String plugindata)` would be for sending to individual clients

I think this makes more sense.

**Comment by hbeni** [comment]
> I think this makes more sense.

Indeed, i think that makes perfect sense. I can always get the session id from the user object easily, too; but this way it's much more easy to iterate and work with. Thanks for the addition, I will test and report back!

**Comment by hbeni** [comment]
tested commit 5734df4ddb2e57

----
> Alright well, I decided on making mumble.client:getUsers() return an ordered table of users, rather than a key=session, value=user pair. This allows you to pass the table without modification to mumble.client:sendPluginData()

Tested OK :ok:

----
> `mumble.user:sendPluginData(String dataID, String plugindata)` would be for sending to individual clients

Tested, but I get a failure:
```lua
client:hook("OnPluginData", function(client, event)
    if event.id:len() > 0 and event.id:find("FGCOM:ICANHAZDATAPLZ") then
        print("OnPluginData(): client asks for data: "..tostring(event.sender))
        event.sender:sendPluginData("FGCOM:TESTREPLY:0", "1234567890")
    end
end)
```

`test/pluginSendtest.lua:62: attempt to call method 'sendPluginData' (a nil value)`

**Comment by bkacjios** [comment]
Turns out I forgot to register that function in the users metatable. Whoops. Fixed!

**Comment by hbeni** [comment]
Just tested e95fda62cca7

EDIT: All is fine. Something went wrong with my compile.
The `event.sender:sendPluginData()` does work like expected, as does the `client:sendPluginData()` with user table

**Comment by hbeni** [comment]
As all is allright, I close this for you, okay?

Thank you again, for your fast response and fix :)
Much appreciated! Awesome lib, making my life easy! :tada:

**Comment by bkacjios** [comment]
No problem. Glad to know someone is making something cool with this side project of mine. :D

**Comment by hbeni** [comment]
Hi @bkacjios 
I think I faced a regression.

The past few days I had the time to upgrade my setup to the release `a85fe47285c7859e6e60ed202eed8ea7d6c64ed8 (HEAD -> master, tag: v2025-02-19`
Since then, it looks I face a very similar problem here again.

It looks like I can't send onto the wire anymore.

The receiving bot prints the plugin messages from other bots (on the old codebase), but not the ones from the commit above.
The sender tries two different mechanics (that are in the docs), and neither message goes out.

I would be very glad If you could have a look to see whats wrong.


--------
**Receiver**
`$ luajit test/pluginSendtest-Rcsv.lua --host=localhost --cert=bot1.pem --key=bot1.key`

```lua
mumble = require("mumble")  -- get the mumble API

local host = "localhost"
local port = 64738
local channel = "fgcom-mumble"
local cert = "bot.pem"
local key  = "bot.key"

-- Parse cmdline args
if arg[1] then
    if arg[1]=="-h" or arg[1]=="--help" then
        print(botname)
        print("usage: "..arg[0].." [opt=val ...]")
        print("  Options:")
        print("    --host=    host to connect to           (default="..host..")")
        print("    --port=    port to connect to           (default="..port..")")
        print("    --channel= channel to join                  (default="..channel..")")
        print("    --cert=    path to PEM encoded cert     (default="..cert..")")
        print("    --key=     path to the certs key        (default="..key..")")
        os.exit(0)
    end
    
    for _, opt in ipairs(arg) do
        _, _, k, v = string.find(opt, "--(%w+)=(.+)")
        if k=="host"    then host=v end
        if k=="port"    then port=v end
        if k=="channel"   then channel=v end
        if k=="cert"    then cert=v end
        if k=="key"     then key=v end
    end
    
end



print("connecting to "..host.." on port "..port.." (cert: "..cert.."; key: "..key.."), joining: '"..channel.."'")
local client = mumble.client()
client:hook("OnConnect", function(client)
    client:auth("test-rcv")
    print("connect and bind: OK")
end)
assert(client:connect(host, port, cert, key))


client:hook("OnServerSync", function(client, event)
    print("Sync done; server greeted with: ", event.welcome_text)
           
    -- try to join fgcom-mumble channel
    local ch = client:getChannel(channel)
    event.user:move(ch)
    print("joined channel "..ch:getName())

    -- Ask present clients for data
    client:sendPluginData("FGCOM:ICANHAZDATAPLZ", "orly!", ch:getUsers())
end)
    
    

client:hook("OnPluginData", function(client, event)
    --["sender"] = mumble.user sender, -- Who sent this data packet
	--["id"]     = Number id,          -- The data ID of this packet
	--["data"]   = String data,        -- The data sent (can be binary data)
	--["receivers"]				= {  -- A table of who is receiving this data
	--	[1] = mumble.user,
	--},
    print("DATA INCOMING FROM="..event.sender:getSession())
    print("  ID="..event.id)
    print("  DATA="..event.data)

end)

mumble.loop()

```

**Sender**
`$ luajit test/pluginSendtest.lua --host=localhost --cert=bot2.pem --key=bot2.key`

```lua
mumble = require("mumble")  -- get the mumble API

local host = "localhost"
local port = 64738
local channel = "fgcom-mumble"
local cert = "bot.pem"
local key  = "bot.key"

-- Parse cmdline args
if arg[1] then
    if arg[1]=="-h" or arg[1]=="--help" then
        print(botname)
        print("usage: "..arg[0].." [opt=val ...]")
        print("  Options:")
        print("    --host=    host to connect to           (default="..host..")")
        print("    --port=    port to connect to           (default="..port..")")
        print("    --channel= channel to join                  (default="..channel..")")
        print("    --cert=    path to PEM encoded cert     (default="..cert..")")
        print("    --key=     path to the certs key        (default="..key..")")
        os.exit(0)
    end
    
    for _, opt in ipairs(arg) do
        _, _, k, v = string.find(opt, "--(%w+)=(.+)")
        if k=="host"    then host=v end
        if k=="port"    then port=v end
        if k=="channel"   then channel=v end
        if k=="cert"    then cert=v end
        if k=="key"     then key=v end
    end
    
end



print("connecting to "..host.." on port "..port.." (cert: "..cert.."; key: "..key.."), joining: '"..channel.."'")
local client = mumble.client()
client:hook("OnConnect", function(client)
    client:auth("test-send")
    print("connect and bind: OK")
end)
assert(client:connect(host, port, cert, key))


local timer = mumble.timer()
client:hook("OnServerSync", function(client, event)
    print("Sync done; server greeted with: ", event.welcome_text)
           
    -- try to join fgcom-mumble channel
    local ch = client:getChannel(channel)
    event.user:move(ch)
    print("joined channel "..ch:getName())
    
    o=0
    timer:start(function(t)
	    o=o+1
        print(o..": send plugin message to all users ")
        users = ch:getUsers()
        u_tbl = {}
        i = 0
        for s,u in pairs(users) do
            i=i+1
            print("  "..i.." ("..s.."): "..u:getName())
            --not advisable: client:sendPluginData("FGCOM:UPD_USR:0", "CALLSIGN=test-"..i, u)
            table.insert(u_tbl, u)
        end
            
        client:sendPluginData("FGCOM:UPD_USR:0", "CALLSIGN=test-"..i, u_tbl)
        client:sendPluginData("FGCOM:UPD_COM:0:0", "FRQ=123,PTT=0"..i, users)
        
    end, 1, 1)

    print("send ok")
end)

client:hook("OnPluginData", function(client, event)
    --["sender"] = mumble.user sender, -- Who sent this data packet
	--["id"]     = Number id,          -- The data ID of this packet
	--["data"]   = String data,        -- The data sent (can be binary data)
	--["receivers"]				= {  -- A table of who is receiving this data
	--	[1] = mumble.user,
	--},

    --print("DATA INCOMING FROM="..event.sender:getSession())
    --print("  ID="..event.id)
    --print("  DATA="..event.data)

    -- Answer data requests
    if event.id:len() > 0 and event.id:find("FGCOM:ICANHAZDATAPLZ") then
        print("OnPluginData(): client asks for data: "..tostring(event.sender))
        event.sender:sendPluginData("FGCOM:TESTREPLY:0", "1234567890")
    end

end)

mumble.loop()

```

**Comment by bkacjios** [comment]
I think I figured out the issue. mumble.channel:getUsers() is returning nothing. Whoops. I'll try to get this fixed in a moment.

**Comment by hbeni** [comment]
Thanks. That looks much better :)
